"""waypoint修正

Revision ID: 4388230b4809
Revises: edb3f89e686f
Create Date: 2024-02-11 14:06:58.247071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4388230b4809'
down_revision = 'edb3f89e686f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_point')
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=140), nullable=False))
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Float(precision=140),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Float(precision=140),
               existing_nullable=False)
        batch_op.drop_column('adress')

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('start_point_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_point_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('waypoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waypoint', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('waypoint_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_waypoint_point_id', 'point', ['waypoint_id'], ['id'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waypoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('waypoint_id')
        batch_op.drop_column('waypoint')

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('end_point_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_point_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=140), nullable=False))
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=140),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=140),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('address')

    op.create_table('_alembic_tmp_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
