"""pointに修正

Revision ID: 5dd5ef542be0
Revises: a5b9e064ec01
Create Date: 2024-02-10 22:52:55.603477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd5ef542be0'
down_revision = 'a5b9e064ec01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('adress', sa.String(length=140), nullable=False),
    sa.Column('latitude', sa.String(length=140), nullable=False),
    sa.Column('longitude', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tweet')
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('favorited')

    op.create_table('tweet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('adress', sa.VARCHAR(length=140), nullable=False),
    sa.Column('latitude', sa.VARCHAR(length=140), nullable=False),
    sa.Column('longitude', sa.VARCHAR(length=140), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('point')
    # ### end Alembic commands ###
