"""routeのstart_point,end_pointに外部キーを挿入

Revision ID: edb3f89e686f
Revises: 5dd5ef542be0
Create Date: 2024-02-10 23:50:44.465999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb3f89e686f'
down_revision = '5dd5ef542be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_point_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_point_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'point', ['end_point_id'], ['id'])
        batch_op.create_foreign_key(None, 'point', ['start_point_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('end_point_id')
        batch_op.drop_column('start_point_id')

    # ### end Alembic commands ###
